---
title: "負の二項分布とガンマ分布の関係"
author: "プログラマたんbot"
date: "2019/7/28"
output:
  pdf_document:
    latex_engine: xelatex
  beamer_presentation:
    pandoc_args:
    - --latex-engine
    - xelatex
documentclass: bxjsarticle
classoption: xelatex,ja=standard
geometry: no
urlcolor: blue
---

```{r load, include=FALSE, warning=FALSE}
## Cited from
## https://keachmurakami.github.io/2016/10/04/Eqnknitr.html
EqnNum_count <- 0
head <- "式"

EqnNum <-
  function(head){
    EqnNum_count <<- EqnNum_count + 1
    return(paste0(head, EqnNum_count))
  }
```

## 負の二項分布

複数の異なる定義があるので、順に説明する。

[Wikipedia](https://en.wikipedia.org/wiki/Negative_binomial_distribution)に従い、負の二項分布を、「1回の試行に確率$p$で成功するとき、$r$回目の失敗までの、成功回数$y$の分布」と定義する。この分布は

$$
NegativeBinomial(y|r,p) = \binom {y+r-1}{y} (1-p)^r p^y \tag{`r EqnNum(head)`} \label{eq:nb_def}
$$

これは$r$回目に失敗するまでに、$y$回成功し$r-1$回失敗する試行の組み合わせと、その確率である。

「[高校数学の美しい物語](https://mathtrain.jp/negativebinom)」の定義は、成功回数$y$を試行回数$z:=y+r$に置き換えて、

$$
\binom {y+r-1}{x} = \binom {y+r-1}{r-1}
$$

であることを用い、

$$
NegativeBinomial(z|r,p) = \binom {z-1}{r-1} (1-p)^r p^{z-r} \tag{`r EqnNum(head)`} \label{eq:nb_def_alt} \\
$$

としたものである。

"[Stan Functions Reference](https://mc-stan.org/docs/2_19/functions-reference-2_19.pdf)"による、別の定義を与える。

$$
NegativeBinomial(y|\alpha,\beta) = \binom {y+\alpha-1}{\alpha-1} (\frac {\beta}{1+\beta})^\alpha (\frac {1}{1+\beta})^y \tag{`r EqnNum(head)`} \label{eq:stan_nb}
$$

[Rのdnbinom関数の説明](https://stat.ethz.ch/R-manual/R-patched/library/stats/html/NegBinomial.html)によると、

$$
NegativeBinomial(y|size,prob) = \frac {\Gamma(y+size)}{\Gamma(size) y!} p^{size} (1-p)^y \tag{`r EqnNum(head)`} \label{eq:dnbinom}
$$

である。これは階乗をガンマ関数におきかえ、 \ref{eq:stan_nb} を以下のように置き換えることで得られる。

$$
\Gamma(k+1) = k!, size := \alpha, \beta := 1/p - 1
$$

## ガンマ分布

[Wikipedia](https://en.wikipedia.org/wiki/Gamma_distribution)によると、ガンマ分布の確率密度関数は

$$
GammaDistribution(x|shape,rate) = \frac {{rate}^{shape}}{\Gamma(shape)} x^{shape-1} e^{-rate*x} \tag{`r EqnNum(head)`} \label{eq:gamma_rate}
$$

である。慣習的に、$\alpha:=shape$, $\beta:=rate$, $\theta:=scale=1/\beta$と表記する。平均$\mathbb{E}[x]$と分散$Var[x]$は、以下の通りである。

$$
\mathbb{E}[x] = \frac {\alpha}{\beta} = \alpha \theta, Var[x] = \frac {\alpha}{{\beta}^2} = \frac {\mathbb{E}[x]}{\beta} = \alpha {\theta}^2 = \mathbb{E}[x] \theta
$$

平均と分散が既知なら(観測値があれば)、負の二項分布のパラメータ$\alpha, \beta$を求めることができる。

$$
\beta = \frac {\mathbb{E}[x]}{Var[x]}, \alpha = \mathbb{E}[x] \beta = \frac {\mathbb{E}[x]}{\theta}
$$

## ガンマ-ポアソン分布

観測値が過分散であるときに、標本には個体差があり、応答変数は個体差に従った分布である、というモデルを適用することがある。例えば発芽率は、n個の種の発芽率$p_i, i\in {1..n}$がある分布に従い、それぞれの種は確率$p_i$で発芽する、と仮定することである。詳しくは、"データ解析のための統計モデリング入門 一般化線形モデル・階層ベイズモデル・MCMC (確率と情報の科学)", 久保拓弥 著, 岩波書店, 2012/5 を参照すること。

ここで個体差をガンマ分布で表現し、それぞれの個体差を説明変数とするポアソン分布にした値が観測される、というモデルを考える。

$$
y \sim PossionDistribution(y), x \sim GammaDistribution(shape,rate) \tag{`r EqnNum(head)`} \label{eq:gamma_poisson}
$$

ガンマ-ポアソン分布を一まとめにして、負の二項分布で表現することができる。証明は[StackExchange](https://stats.stackexchange.com/questions/263063/relationship-between-negative-binomial-distribution-and-bayesian-poisson-with-ga)にあるが、長いのでここには載せない。

## 平均と分散

これまでに挙げた文献から、平均と分散を引用する。

### NB($\alpha, \beta$)の平均と分散

負の二項分布の定義 \ref{eq:stan_nb} において、平均$\mathbb{E}[y]$と分散$Var[y]$は、以下の通りである。
$$
\mathbb{E}[y] = \frac {\alpha}{\beta}, Var[y] = \frac {\alpha}{{\beta}^2}(\beta+1) = \mathbb{E}[y] (1+\frac {1}{\beta}) \tag{`r EqnNum(head)`} \label{eq:nb_ab_mu}
$$

であり、平均と分散が既知なら(観測値があれば)、負の二項分布のパラメータ$\alpha, \beta$を求めることができる。

$$
\beta = \frac {\mathbb{E}[y]}{Var[y] - \mathbb{E}[y]}, \alpha = \mathbb{E}[y] * \beta
$$

負の二項分布の代わりに、ガンマ-ポアソン分布 \ref{eq:gamma_poisson} におけるガンマ分布 \ref{eq:gamma_rate} のパラメータで表現することを考える。ポアソン分布$y \sim poisson(\lambda)$の平均$\mathbb{E}[y]$と分散$Var[y]$は

$$
\mathbb{E}[y] = \lambda, Var[y] = \lambda
$$

であり、[StackExchange](https://math.stackexchange.com/questions/1780385/mean-and-variance-of-the-sum-of-cgf-gamma-and-poisson-distribution)によると、独立な期待値と分散の加法性(共分散が0)から、$x$がガンマ分布$Gamma(\alpha_{gamma}, \beta_{gamma})$に従うとき、

$$
\mathbb{E}[y] = \lambda= \mathbb{E}[x], Var[y] = Var[Gamma(\alpha_{gamma}, \beta_{gamma})] + \lambda
$$

$$
\mathbb{E}[x] = \mathbb{E}[Gamma(\alpha_{gamma}, \beta_{gamma})] = \frac {\alpha_{gamma}}{\beta_{gamma}}
$$

$$
Var[x] = \mathbb{E}[x] + Var[Gamma(\alpha_{gamma}, \beta_{gamma}] = \frac {\alpha_{gamma}}{\beta_{gamma}} (1 + \frac{1} {\beta_{gamma}}) = \mathbb{E}[x] (1 + \frac{1} {\beta_{gamma}})
$$

である。つまり、$\alpha=\alpha_{gamma}, \beta=\beta_{gamma}$が成り立つ。

### NB(size, prob)の平均と分散

負の二項分布の定義 \ref{eq:dnbinom} において、平均$\mathbb{E}[y]$と分散$Var[y]$は、以下の通りである。
$$
\mathbb{E}[y] = size \frac {1-prob}{prob}, Var[y]= size \frac {1-prob}{{prob}^2} = \frac {\mathbb{E}[y]}{prob}
$$

であり、平均と分散が既知なら(観測値があれば)、負の二項分布のパラメータ$size, prob$を求めることができる。

$$
prob = \frac {\mathbb{E}[y]}{Var[y]}, size = Var[y] * \frac {{prob}^2}{1-prob} = \frac {{\mathbb{E}[y]}^2}{Var[y] - \mathbb{E}[y]}
$$

負の二項分布の代わりに、ガンマ-ポアソン分布 \ref{eq:gamma_poisson} におけるガンマ分布 \ref{eq:gamma_rate} のパラメータで表現することを考える。先ほどとは逆に、$x$がガンマ分布$Gamma(\alpha_{gamma}, \beta_{gamma})$に従うとしてボトムアップに考える。

$$
\beta = \frac {Var(x)}{\mathbb{E}(x)} = \frac {Var(y) - \mathbb{E}(x)}{\mathbb{E}(x)} = \frac {Var(y) - \mathbb{E}(y)}{\mathbb{E}(y)} = \frac {1}{p} - 1
$$

$$
\alpha = \frac {\mathbb{E}[x]}{\beta} = \frac {\mathbb{E}[y]}{\beta} = size
$$

つまり、$\alpha=size, \beta=1/p - 1$が成り立つ。これは\ref{eq:stan_nb}と\ref{eq:dnbinom}の関係であった。

## 再生性

### NB(size, prob)の再生性

負の二項分布$NB(size, prob)$は$size$に対して再生性がある。つまり

$$
NB(size_A+size_B, prob) = NB(size_A, prob) + NB(size_B, prob)
$$

$$
NB(y|size_A+size_B, prob) = \sum_{i=0}^y {NB(i|size_A, prob) * NB(y-i|size_B, prob)}
$$

負の二項分布のモーメント母関数

$$
M_x(t) = (\frac {p}{1-(1-p)e^t})^r
$$

の定義から明らかと言えるが、ここではガンマ関数の引数が整数に限るつまり階乗に置き換えられるものとして、sum記号の中を幾何的に解く。

言葉で書くと、$r$回目に失敗するまでに、$y$回成功するのは、$i$回成功してから$y-i$成功することと同じ、という意味である。直感的な証明は以下の通りである。\ref{eq:dnbinom} より、

$$
NB(y|size_A+size_B, prob) = \sum_{i=0}^y {\frac {\Gamma(i+size_A)}{\Gamma(size_A) i!} p^{size_A} (1-p)^i \frac {\Gamma(y-i+size_B)}{\Gamma(size_B) (y-i)!} p^{size_B} (1-p)^{y-i} }
$$

$$
= p^{size_A + size_B} (1-p)^y \sum_{i=0}^y { \frac {\Gamma(i+size_A)}{\Gamma(size_A) i!} \frac {\Gamma(y-i+size)}{\Gamma(size) (y-i)!} }
$$

碁盤目の状の街があり、縦$m$区間、横$n$区間あるとする。このとき待ちの左上の端から右下の端まで、右または下方向に移動することを考える。つまり縦、縦、横、縦、... と移動する。このとき左上の端から右下の端までの経路は、$(m+n)!/(m!n!)$通りある。

なぜなら縦同士、横同士の移動を移動時の座標に基づいて、縦1、縦2、横1、縦3、と区別したときの経路数は$(m+n)!$であるが、実は縦同士、横同士の移動を区別しないので、$m!*n!$で割ると、上記の通りになるからである。これはm+n個からm個取り出す組み合わせの数である。

ここで縦$y$区間、横$size_A+size_B-1$区間ある街を考える。ここで、

1. 縦$i$区間、横$size_A-1$区間移動して
1. 横に1区間移動して
1. 縦$y-i$区間、横$size_B-1$区間移動する

経路の数を考え、取りうるすべての$i \in {0..y}$について足す。これは$i$回成功してから$y-i$成功する経路を漏れなく重複なく数えることと同じである。よって、

$$
\binom {y+size_A+size_B-1}{y} = \sum_{i=0}^y { \binom {y+size_A-1}{y} \binom {y+size_B-1}{y} }
$$

である。

### ガンマ分布の再生性

ガンマ分布$GammaDistribution(\alpha, \beta)$は$\alpha=shape$に対して再生性がある。つまり

$$
x_A \sim GammaDistribution(\alpha_A, \beta), x_B \sim GammaDistribution(\alpha_B, \beta)
$$

なら

$$
x_A + x_B \sim GammaDistribution(\alpha_A+\alpha_B, \beta)
$$

である。

ガンマ分布のモーメント母関数
$$
M_x(t) = (1 + t/\beta)^{\alpha}
$$

の定義から明らかと言えるが、証明は[こちら](https://k-san.link/gamma-reproductive/)。
