FROM stan

RUN apt-get install -y clang-12 lldb-12 lld-12

RUN Rscript -e 'remotes::install_version("Rcpp")'
RUN Rscript -e 'remotes::install_version("BH")'
RUN Rscript -e 'remotes::install_version("devtools")'
RUN Rscript -e 'remotes::install_version("data.table")'
RUN Rscript -e 'remotes::install_version("microbenchmark")'
RUN Rscript -e 'devtools::install_github("hadley/emo")'
RUN Rscript -e 'remotes::install_version("lpSolve")'
RUN Rscript -e 'remotes::install_version("zeallot")'

RUN mkdir -p /home/rstudio/.R
RUN echo 'CXX20="clang++-12"' >> /home/rstudio/.R/Makevars
RUN chown rstudio:rstudio /home/rstudio/.R /home/rstudio/.R/Makevars
