version: '3'
services:
  streamlit_build:
    build: .
    image: streamlit_build
    user: jovyan
    ports:
      - 8888:8888
      - 8501:8501
    environment:
      - DISPLAY=:99
      - USE_HEADLESS_BROWSER=1
    volumes:
      - .:/home/jovyan/work
