[package]
name = "par_iter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.19"
rand = "0.8.5"
rayon = "1.7.0"
